export const CHANGE_FILTER_SORTING = "CHANGE_FILTER_SORTING";
export const CHANGE_FILTER_TAGS = "CHANGE_FILTER_TAGS";
export const CHANGE_FILTER_BRANDS = "CHANGE_FILTER_BRANDS";
export const CHANGE_FILTER_TYPES = "CHANGE_FILTER_TYPES";
